# Generated by Django 5.2.8 on 2025-11-13 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('pelicula', 'Película'), ('serie', 'Serie'), ('documental', 'Documental')], max_length=20)),
                ('fecha_lanzamiento', models.DateField()),
                ('categoria', models.IntegerField()),
                ('capitulos', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'contenido',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('fecha_fundacion', models.DateField()),
                ('pais_origen', models.CharField(default='Japón', max_length=50)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.CharField(choices=[('soporte', 'Soporte al Cliente'), ('tecnico', 'Técnico'), ('contenido', 'Gestión de Contenido'), ('marketing', 'Marketing'), ('administracion', 'Administración')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='app_Crunchyroll.empresa')),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calidad_video', models.CharField(max_length=20)),
                ('num_dispositivos', models.IntegerField()),
                ('beneficio_extra', models.TextField()),
                ('descarga_offline', models.BooleanField(default=False)),
                ('contenidos_exclusivos', models.ManyToManyField(blank=True, related_name='suscripciones_exclusivas', to='app_Crunchyroll.contenido')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='app_Crunchyroll.empresa')),
            ],
            options={
                'db_table': 'suscripcion',
            },
        ),
        migrations.AddField(
            model_name='contenido',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_principales', to='app_Crunchyroll.suscripcion'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_principales', to='app_Crunchyroll.suscripcion')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='usuarios_premium',
            field=models.ManyToManyField(blank=True, related_name='suscripciones_adicionales', to='app_Crunchyroll.usuario'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal'), ('transferencia', 'Transferencia Bancaria'), ('crypto', 'Criptomoneda')], max_length=20)),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='completada', max_length=20)),
                ('codigo_transaccion', models.CharField(max_length=100, unique=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_gestionadas', to='app_Crunchyroll.empleado')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='app_Crunchyroll.suscripcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='app_Crunchyroll.usuario')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
    ]
