# Generated by Django 5.2.8 on 2025-11-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Crunchyroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='contenido/', verbose_name='Portada del contenido'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/', verbose_name='Foto del empleado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/', verbose_name='Logo de la empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Avatar del usuario'),
        ),
    ]
