# Generated by Django 5.2.8 on 2025-11-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Crunchyroll', '0002_contenido_portada_empleado_foto_empresa_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='tipo',
            field=models.CharField(choices=[('anime', 'Anime'), ('pelicula', 'Película'), ('manga', 'Manga')], max_length=20),
        ),
    ]
